CREATE DATABASE RH_UPPER_SEX

USE RH_UPPER_SEX

CREATE TABLE ESTADO
(CD_ESTADO INT IDENTITY(1,1) NOT NULL,
NM_ESTADO VARCHAR(30) NOT NULL,
DS_SIGLA VARCHAR(2) NOT NULL,
CONSTRAINT PK_ESTADO PRIMARY KEY(CD_ESTADO),
CONSTRAINT UNICO_ESTADO UNIQUE(NM_ESTADO),
CONSTRAINT UNICA_SIGLA UNIQUE(DS_SIGLA))

CREATE TABLE CIDADE
(CD_CIDADE INT IDENTITY(1,1) NOT NULL,
NM_CIDADE VARCHAR(50) NOT NULL,
CD_ESTADO INT NOT NULL,
CONSTRAINT PK_CIDADE PRIMARY KEY(CD_CIDADE),
CONSTRAINT FK_CIDADE FOREIGN KEY(CD_ESTADO) REFERENCES ESTADO(CD_ESTADO))

CREATE TABLE DEPTO
(CD_DEPTO INT IDENTITY(1,1) NOT NULL,
NM_DEPTO VARCHAR(30) NOT NULL,
CONSTRAINT PK_DEPTO PRIMARY KEY(CD_DEPTO),
CONSTRAINT UNICO_DEPTO UNIQUE(NM_DEPTO))

CREATE TABLE BAIRRO
(CD_BAIRRO INT IDENTITY(1,1) NOT NULL,
NM_BAIRRO VARCHAR(30) NOT NULL,
CONSTRAINT PK_BAIRRO PRIMARY KEY(CD_BAIRRO))

CREATE TABLE FUNCIONARIO
(CD_FUNCIONARIO INT IDENTITY(1,1) NOT NULL,
NM_FUNCIONARIO VARCHAR(50) NOT NULL,
NR_RG VARCHAR(15) NULL,
NR_CPF VARCHAR(11) NULL,
DS_SEXO VARCHAR(1) NULL,
VL_SALARIO NUMERIC(18,2) NULL,
DT_ADMISSAO DATE NULL,
DS_LOGRADOURO VARCHAR(50) NULL,
DS_COMPLEMENTO VARCHAR(15) NULL,
DS_CEP VARCHAR(8) NULL,
NR_QT_DIAS INT,
CD_BAIRRO INT NOT NULL,
CD_CIDADE INT NOT NULL,
CD_DEPTO INT NOT NULL,
CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(CD_FUNCIONARIO),
CONSTRAINT CHECK_SEXO CHECK(DS_SEXO IN ('F','M')),
CONSTRAINT FK_FUNCIONARIO_BAIRRO FOREIGN KEY(CD_BAIRRO) REFERENCES BAIRRO(CD_BAIRRO),
CONSTRAINT FK_FUNCIONARIO_CIDADE FOREIGN KEY(CD_CIDADE) REFERENCES CIDADE(CD_CIDADE),
CONSTRAINT FK_FUNCIONARIO_DEPTO FOREIGN KEY(CD_DEPTO) REFERENCES DEPTO(CD_DEPTO))

--CRIAÇÃO DA TABELA PROJETO
CREATE TABLE PROJETO
(CD_PROJETO INT IDENTITY(1,1) NOT NULL,
NM_PROJETO VARCHAR(50) NOT NULL,
DT_INICIO DATE NULL,
DT_FIM DATE NULL,
CONSTRAINT PK_PROJETO PRIMARY KEY(CD_PROJETO))


--CRIAÇÃO DA TABELA ASSOCIATIVA FUNCIONARIO_PROJETO
CREATE TABLE FUNCIONARIO_PROJETO
(CD_FUNCIONARIO INT NOT NULL,
CD_PROJETO INT NOT NULL,
CONSTRAINT FK_FUNCIONARIO_PROJETO FOREIGN KEY(CD_FUNCIONARIO) REFERENCES FUNCIONARIO(CD_FUNCIONARIO),
CONSTRAINT FK_PROJETO_FUNCIONARIO FOREIGN KEY(CD_PROJETO) REFERENCES PROJETO(CD_PROJETO))

--DADOS DO ESTADO
INSERT INTO ESTADO VALUES ('SÃO PAULO','SP')
INSERT INTO ESTADO VALUES ('PARANÁ','PR')
INSERT INTO ESTADO VALUES ('RIO DE JANEIRO','RJ')
INSERT INTO ESTADO VALUES ('MINAS GERAIS','MG')

--DADOS DAS CIDADES
INSERT INTO CIDADE VALUES ('SÃO PAULO',1)
INSERT INTO CIDADE VALUES ('SANTOS',1)
INSERT INTO CIDADE VALUES ('OSASCO',1)

INSERT INTO CIDADE VALUES ('CURITIBA',2)
INSERT INTO CIDADE VALUES ('LONDRINA',2)
INSERT INTO CIDADE VALUES ('MARINGÁ',2)

INSERT INTO CIDADE VALUES ('RIO DE JANEIRO',3)
INSERT INTO CIDADE VALUES ('BÚZIOS',3)
INSERT INTO CIDADE VALUES ('NITERÓI',3)

INSERT INTO CIDADE VALUES ('BELO HORIZONTE',4)
INSERT INTO CIDADE VALUES ('OURO FINO',4)
INSERT INTO CIDADE VALUES ('GOVERNADOR VALADARES',4)

--DADOS DE DEPTO
INSERT INTO DEPTO VALUES ('RH')
INSERT INTO DEPTO VALUES ('TI')
INSERT INTO DEPTO VALUES ('DIRETORIA')
INSERT INTO DEPTO VALUES ('CONTAS A PAGAR')
INSERT INTO DEPTO VALUES ('CONTAS A RECEBER')
INSERT INTO DEPTO VALUES ('ALMOXARIFADO')

--DADOS DE BAIRRO
INSERT INTO BAIRRO VALUES ('BELA VISTA')
INSERT INTO BAIRRO VALUES ('MOEMA')
INSERT INTO BAIRRO VALUES ('PARAÍSO')
INSERT INTO BAIRRO VALUES ('LIBERDADE')
INSERT INTO BAIRRO VALUES ('BRÁS')
INSERT INTO BAIRRO VALUES ('JARDINS')

--DADOS DE FUNCIONARIO
INSERT INTO FUNCIONARIO VALUES ('ANA','111','222','F',10000,'01/03/2000','AV IBIRAPUERA, 1000',NULL,'02011030',NULL,1,1,1)
INSERT INTO FUNCIONARIO VALUES ('SILVIO','222','909','M',9000,'02/04/2000','AV BRASIL, 900','APTO 11','04011030',NULL,2,2,2)
INSERT INTO FUNCIONARIO VALUES ('RITA','333','324','F',7500,'03/05/2000','AV LIBERDADE, 100','TORRE A','04511030',NULL,3,3,3)
INSERT INTO FUNCIONARIO VALUES ('FERNADO','444','390','M',3500,'04/06/2000','RUA TOPÁZIO, 431','CASA 1','02911030',NULL,3,4,2)
INSERT INTO FUNCIONARIO VALUES ('BRUNA','555','678','F',4100,'05/07/2000','AL UAPES, 800',NULL,'06111030',NULL,4,4,1)
INSERT INTO FUNCIONARIO VALUES ('SANDRO','666','190','M',11000,'06/08/2000','AV PAULISTA, 1100','BLOCO A','07711030',NULL,2,1,3)
INSERT INTO FUNCIONARIO VALUES ('JULIA','777','341','F',5600,'06/09/2000','RUA AUGUSTA, 109',NULL,'08811030',NULL,3,2,1)
INSERT INTO FUNCIONARIO VALUES ('CARLOS','888','560','M',6500,'05/10/2000','RUA JUNDIAÍ, 830','FUNDOS','09911030',NULL,4,4,4)
INSERT INTO FUNCIONARIO VALUES ('FELIPE','999','909','M',7200,'09/11/2000','AV IBIRAPUERA, 2100','TÉRREO','14011030',NULL,4,2,4)
INSERT INTO FUNCIONARIO VALUES ('EDUARDO','101','392','M',8100,'10/12/2000','AL BARROS, 111',NULL,'24011030',NULL,5,5,5)
INSERT INTO FUNCIONARIO VALUES ('FLAVIA','202','777','F',5200,'11/01/2000','RUA GAIVOTA, 700','APTO 23','34011030',NULL,3,4,5)
INSERT INTO FUNCIONARIO VALUES ('MARIA','303','156','F',14000,'20/02/2000','AV MIRUNA, 3000',NULL,'44011030',NULL,2,4,6)
INSERT INTO FUNCIONARIO VALUES ('VALERIA','404','310','F',13000,'30/03/2000','AV VERGUEIRO, 6500','CASA A1','54011030',NULL,3,3,4)
INSERT INTO FUNCIONARIO VALUES ('ROBERTO','505','292','M',11000,'15/04/2000','RUA PRATES, 20',NULL,'64011030',NULL,2,4,4)
INSERT INTO FUNCIONARIO VALUES ('VANIA','606','288','F',9000,'17/04/2000','AV SANTO AMARO, 3400','APTO 60','74011030',NULL,4,4,4)
INSERT INTO FUNCIONARIO VALUES ('WALTER','707','772','M',8000,'14/06/2000','RUA DO PARAÍSO, 90','APTO 11','84011030',NULL,1,1,1)
INSERT INTO FUNCIONARIO VALUES ('VANESSA','808','201','F',70000,'11/07/2000','RUA RAFAEL DE BARROS, 211',NULL,'94011030',NULL,4,1,1)


INSERT INTO PROJETO VALUES ('RH','01/03/2022','31/03/2022')
INSERT INTO PROJETO VALUES ('CONTAS A PAGAR','01/04/2022','30/04/2022')
INSERT INTO PROJETO VALUES ('CONTAS A RECEBER','01/06/2022','30/06/2022')
INSERT INTO PROJETO VALUES ('ALMOFARIFADO','01/07/2022','30/07/2022')
INSERT INTO PROJETO VALUES ('REDES','01/08/2022','30/08/2022')
--
INSERT INTO FUNCIONARIO_PROJETO VALUES (1,5)
INSERT INTO FUNCIONARIO_PROJETO VALUES (2,5)
INSERT INTO FUNCIONARIO_PROJETO VALUES (3,2)
INSERT INTO FUNCIONARIO_PROJETO VALUES (1,3)
INSERT INTO FUNCIONARIO_PROJETO VALUES (4,5)
INSERT INTO FUNCIONARIO_PROJETO VALUES (5,5)
INSERT INTO FUNCIONARIO_PROJETO VALUES (6,2)
INSERT INTO FUNCIONARIO_PROJETO VALUES (7,3)
INSERT INTO FUNCIONARIO_PROJETO VALUES (8,3)
INSERT INTO FUNCIONARIO_PROJETO VALUES (9,5)
INSERT INTO FUNCIONARIO_PROJETO VALUES (10,5)
INSERT INTO FUNCIONARIO_PROJETO VALUES (11,2)
INSERT INTO FUNCIONARIO_PROJETO VALUES (13,3)
INSERT INTO FUNCIONARIO_PROJETO VALUES (14,3)
INSERT INTO FUNCIONARIO_PROJETO VALUES (15,5)
INSERT INTO FUNCIONARIO_PROJETO VALUES (16,5)
INSERT INTO FUNCIONARIO_PROJETO VALUES (17,2)
INSERT INTO FUNCIONARIO_PROJETO VALUES (12,3)
INSERT INTO FUNCIONARIO_PROJETO VALUES (1,1)
INSERT INTO FUNCIONARIO_PROJETO VALUES (2,2)
INSERT INTO FUNCIONARIO_PROJETO VALUES (3,3)
INSERT INTO FUNCIONARIO_PROJETO VALUES (1,4)
INSERT INTO FUNCIONARIO_PROJETO VALUES (4,1)
INSERT INTO FUNCIONARIO_PROJETO VALUES (5,2)
INSERT INTO FUNCIONARIO_PROJETO VALUES (6,3)
INSERT INTO FUNCIONARIO_PROJETO VALUES (7,4)
INSERT INTO FUNCIONARIO_PROJETO VALUES (8,5)
INSERT INTO FUNCIONARIO_PROJETO VALUES (9,1)
INSERT INTO FUNCIONARIO_PROJETO VALUES (10,2)
INSERT INTO FUNCIONARIO_PROJETO VALUES (11,3)
INSERT INTO FUNCIONARIO_PROJETO VALUES (12,4)
INSERT INTO FUNCIONARIO_PROJETO VALUES (13,5)
INSERT INTO FUNCIONARIO_PROJETO VALUES (14,1)
INSERT INTO FUNCIONARIO_PROJETO VALUES (15,2)
INSERT INTO FUNCIONARIO_PROJETO VALUES (16,3)
INSERT INTO FUNCIONARIO_PROJETO VALUES (17,4)
INSERT INTO FUNCIONARIO_PROJETO VALUES (12,5)



select * from FUNCIONARIO
--1
SELECT NM_FUNCIONARIO,DS_SEXO,DT_ADMISSAO,VL_SALARIO,NM_BAIRRO,NM_CIDADE,NM_ESTADO,
NM_DEPTO
FROM FUNCIONARIO AS F
INNER JOIN BAIRRO AS B ON B.CD_BAIRRO=F.CD_BAIRRO
INNER JOIN CIDADE AS C ON C.CD_CIDADE=F.CD_CIDADE
INNER JOIN ESTADO AS E ON E.CD_ESTADO=C.CD_ESTADO
INNER JOIN DEPTO AS D ON D.CD_DEPTO=F.CD_DEPTO
INNER JOIN FUNCIONARIO_PROJETO FP ON F.CD_FUNCIONARIO=FP.CD_FUNCIONARIO
INNER JOIN PROJETO AS P ON P.CD_PROJETO=FP.CD_PROJETO
WHERE YEAR (DT_ADMISSAO)=2000 AND NM_DEPTO='RH' AND DS_SIGLA='SP'
ORDER BY NM_ESTADO, NM_CIDADE, NM_FUNCIONARIO ASC


--2
SELECT NM_FUNCIONARIO,DS_SEXO,DT_ADMISSAO,VL_SALARIO FROM FUNCIONARIO
WHERE CD_FUNCIONARIO IN (SELECT CD_FUNCIONARIO FROM FUNCIONARIO_PROJETO 
WHERE CD_PROJETO IN (SELECT CD_PROJETO FROM  PROJETO WHERE NM_PROJETO='CONTAS A RECEBER'))
AND VL_SALARIO>5000
ORDER BY VL_SALARIO DESC

--3
SELECT NM_FUNCIONARIO,DS_SEXO,DT_ADMISSAO,VL_SALARIO, NM_DEPTO
FROM FUNCIONARIO AS F 
INNER JOIN DEPTO AS D ON D.CD_DEPTO=F.CD_DEPTO
WHERE VL_SALARIO=7500 OR VL_SALARIO=9000 OR VL_SALARIO=4000
ORDER BY NM_DEPTO, NM_FUNCIONARIO

--4
SELECT NM_FUNCIONARIO,DS_SEXO,VL_SALARIO,NM_BAIRRO
FROM FUNCIONARIO AS F
INNER JOIN BAIRRO AS B ON B.CD_BAIRRO=F.CD_BAIRRO
WHERE DS_SEXO='F' AND NM_BAIRRO='BELA VISTA' AND VL_SALARIO >= 5000
AND VL_SALARIO <=10000

--
CREATE VIEW VW_GERAL
AS
SELECT F.CD_FUNCIONARIO,NM_FUNCIONARIO,DS_SEXO,DT_ADMISSAO,VL_SALARIO,B.CD_BAIRRO,NM_BAIRRO,
D.CD_DEPTO,NM_DEPTO,C.CD_CIDADE,NM_CIDADE,E.CD_ESTADO,NM_ESTADO,DS_SIGLA,P.CD_PROJETO,NM_PROJETO,
DT_INICIO,DT_FIM
FROM FUNCIONARIO AS F
INNER JOIN BAIRRO AS B ON B.CD_BAIRRO=F.CD_BAIRRO
INNER JOIN CIDADE AS C ON C.CD_CIDADE=F.CD_CIDADE
INNER JOIN ESTADO AS E ON E.CD_ESTADO=C.CD_ESTADO
INNER JOIN DEPTO AS D ON D.CD_DEPTO=F.CD_DEPTO
INNER JOIN FUNCIONARIO_PROJETO AS FP ON F.CD_FUNCIONARIO=FP.CD_FUNCIONARIO
INNER JOIN PROJETO AS P ON P.CD_PROJETO=FP.CD_PROJETO
--
SELECT * FROM VW_GERAL



--ATUALIZAR DADOS NA TABELA SEM CONDIÇÃO WHERE
UPDATE FUNCIONARIO SET VL_SALARIO=VL_SALARIO + 500
WHERE YEAR (DT_ADMISSAO)=2000

SELECT NM_FUNCIONARIO, VL_SALARIO, DT_ADMISSAO FROM FUNCIONARIO
WHERE YEAR (DT_ADMISSAO) = 2000
ORDER BY NM_FUNCIONARIO